// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeLQ6_pBhFVtthqLRtmg_vyUuX8O30k_4',
    appId: '1:1012145982683:web:0a2159b08be0836f7990fe',
    messagingSenderId: '1012145982683',
    projectId: 'resq-f6c73',
    authDomain: 'resq-f6c73.firebaseapp.com',
    storageBucket: 'resq-f6c73.firebasestorage.app',
    measurementId: 'G-E8KGL69DTX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDABxxer_FFpXFCEi6YVHf75eZScbanwe4',
    appId: '1:1012145982683:android:7a130949d9db986e7990fe',
    messagingSenderId: '1012145982683',
    projectId: 'resq-f6c73',
    storageBucket: 'resq-f6c73.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCx5pDmtgkDuXIcVozv_tu4rrxUvDXEaKg',
    appId: '1:1012145982683:ios:0cae8c12ff79f5647990fe',
    messagingSenderId: '1012145982683',
    projectId: 'resq-f6c73',
    storageBucket: 'resq-f6c73.firebasestorage.app',
    iosBundleId: 'com.example.chatbotLini',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCx5pDmtgkDuXIcVozv_tu4rrxUvDXEaKg',
    appId: '1:1012145982683:ios:0cae8c12ff79f5647990fe',
    messagingSenderId: '1012145982683',
    projectId: 'resq-f6c73',
    storageBucket: 'resq-f6c73.firebasestorage.app',
    iosBundleId: 'com.example.chatbotLini',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCeLQ6_pBhFVtthqLRtmg_vyUuX8O30k_4',
    appId: '1:1012145982683:web:0bef60d64ba4580c7990fe',
    messagingSenderId: '1012145982683',
    projectId: 'resq-f6c73',
    authDomain: 'resq-f6c73.firebaseapp.com',
    storageBucket: 'resq-f6c73.firebasestorage.app',
    measurementId: 'G-XK5N8S25GY',
  );
}
